# change the followings to match your Github username and repo name
baseurl: "/jimmy.github.io" # the name of your github repo
url: "https://jimmy586.github.io/jimmy.github.io/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Mananjara Jimmy VATOSOA"
description: Cloud Engineer | Software Engineer

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Mananjara Jimmy VATOSOA
author-bio: true  # change to false to hide
author-image: profile_home.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: RESUME
  permalink: {site.baseurl}/assets/raw/RESUME.pdf
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/Jimmy586
linkedin: https://linkedin.com/in/mananjara-jimmy.vatosoa
medium: false
google-scholar: false
email: contact@vatosoamananjara-jimmy.com

# footer information
footer-msg: "Powered using Tailpages"
footer-msg-link: https://github.com/Jimmy586

# google analytics
google-analytics: G-Q7Q1DLKRB4

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

# collections
collections_dir: collections
collections:
  - academics
  - projects
